### ISSUE TITLE
Compiling Error with vs2017

### ISSUE THREAD

**Issue by 461353349** [louipc/opennurbs#1]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2039	“line_to_close_contour”: 不是“FT_Outline_Funcs_”的成员	opennurbs_public_staticlib	d:\project\cadmodel\nurbs\opennurbs\opennurbs-61\opennurbs_freetype.cpp	2193

**Comment by louipc** [comment]
On Thu 27 Dec 2018 00:50 -0800, 461353349 wrote:
> 严重性	代码	说明	项目	文件	行	禁止显示状态
> 错误	C2039	“line_to_close_contour”: 不是“FT_Outline_Funcs_”的成员	opennurbs_public_staticlib	d:\project\cadmodel\nurbs\opennurbs\opennurbs-61\opennurbs_freetype.cpp	2193	

Hello you may like to try the new version that I just pushed a few minutes ago.

I cannot offer support for this software. This is only a mirror.
Please contact mcneel for support. https://discourse.mcneel.com/c/opennurbs
Also, in 2018 they have finally started publishing code revisions publicly.
See https://github.com/mcneel/opennurbs

Good luck.

**Comment by 461353349** [comment]
It is Fine! Thanks @louipc
