### ISSUE TITLE
Internal compiler error at line 670 in opennurbs_lookup.cpp

### ISSUE THREAD

**Issue by zhanshenman** [louipc/opennurbs#2]
My operating system is win10, and my compiler is visual studio 2022. I get a compiler error below.:

F:\vcpkg\vcpkg\buildtrees\pcl\src\ade837d55c-9cde649e93.clean\surface\src\3rdparty\opennurbs\opennurbs_lookup.cpp(670) : fatal error C1001: Internal compiler error.

**Comment by louipc** [comment]
New development is at https://github.com/mcneel/opennurbs
